FROM ultralytics/ultralytics:latest-cpu

# working directory
WORKDIR /app

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

EXPOSE 8000

# Command to start the service using uvicorn
CMD ["uvicorn", "detect:app", "--host", "0.0.0.0", "--port", "8000"]